### ISSUE TITLE
Upgrade the TFE prebuilt provider to v0.31.0 (or upgrade to v0.32.0 when released)

### ISSUE THREAD

**Issue by nikolay** [hashicorp/cdktf-repository-manager#74]
The version you're anchored to (v0.26.1) is almost a year old! The choice to use CDKTF should not come with a major compromise and require a downgrade in production and refactoring states (in this case, importing resources against older versions). TFE is used by paying customers who should get a better experience, I believe! Those using older versions in production can always use an older version of the prebuilt provider.

As a side note, I saw you upgraded azurerm to a major version bump, but your CDK prebuild provider was just a patch build. I realize the challenges with complex compound versions in SemVer, but at least when the provider is upgraded to a major new version, the CDKTF prebuild provider's version should also have a major bump.

**Comment by nikolay** [comment]
@DanielMSchmidt I submitted a PR to use the proper variable set support, which is only available in v0.33 (the earlier versions use now deprecated way to configure which workspaces use which sets). Please, review: https://github.com/hashicorp/cdktf-repository-manager/pull/77

**Comment by DanielMSchmidt** [comment]
The new version is released, closing this
